### PR TITLE
fix: remove KEYCLOAK_URL param from OpenShift template

### PR DESCRIPTION
**Pull request by darahayes**
The secure-api server does not make use of the KEYCLOAK_URL env variable anymore so there is no need for it in the template.

Additionally, while working on the integration pieces between keycloak, secure-api, custom runtime connector and android app, we found that the `secure-app-realm.json` file cannot be imported into an existing realm. Keycloak throws up strange errors. 

This is unfortunate because we'd like to use the keycloak realm that's created as part of the provision from the keycloak APB. This 'default' realm already has all of the secrets and config maps set up in OpenShift, which can then be consumed by the API without any effort.

I found that by using the existing JSON file to create a new realm, I was then able to export that realm and the resulting JSON file could be imported into the existing blank realm created as part of the provision. I've added this additional JSON file as it will most likely be needed by whoever records the demo video related to [this epic](https://trello.com/c/ngoT5fZg/41-13-as-a-developer-i-want-to-be-able-to-connect-my-android-app-to-a-custom-backend-service-which-is-protected-by-keycloak-such-th). @aliok has been using it with his side of the integration work.

### CODE REVIEW

**Comment by tomjackman** [comment]
@darahayes What version of Keycloak are you using that caused the error? I've tested on v3.3 and v4.0 beta and I don't see any import errors.

**Comment by darahayes** [comment]
@TommyJ1994 Using the keycloak-apb so version number is 3.4.3.Final

Maybe I wasn't clear enough. Imports are working. It is possible to import the existing file which results in an entirely new realm being created.

Partial imports are not working, i.e. import the json file into an existing blank realm. This is the use case we would like because the keycloak-apb creates a new realm as part of the provision and then inserts credentials and details for that realm into secrets and config maps.

It would be really handy to be able to do a partial import into the realm created by the keycloak-apb because the alternative is to create another realm and then manually update the configmaps and secrets that will be consumed by both the api-server and the application.

**Comment by aliok** [comment]
@darahayes This is not blocking the demo video IMO: https://trello.com/c/ngoT5fZg/41-13-as-a-developer-i-want-to-be-able-to-connect-my-android-app-to-a-custom-backend-service-which-is-protected-by-keycloak-such-th

I think as with other tasks, we can live with it. Unless @TommyJ1994 has an easy solution for us.

**Comment by aliok** [comment]
+1 on removing those params from the template.

**Comment by tomjackman** [comment]
@darahayes Cool, yeah the import is failing as the `secure-app-realm.json` contains the full realm data including the user data. Partial imports don't handle user data so this causes the error.

I think a partial import file is fine for this use case - Is it possible to mention in the filename the work Partial? eg `secure-app-partial-export-realm.json` just to make it clear that this is the result of a partial export and that this file can't be used to create a realm, as it causes an error. 

I'll also see if I can write a more minimal partial export JSON file as exports through the Keycloak UI/CLI outputs lots of unnecessary data and makes maintenance a bit trickier.

**Comment by darahayes** [comment]
@aliok agreed it's not blocking but it's the simplest way to get the environment set up. It would help help whoever inevitably has to go through the setup and record the demo video. Happy to remove the JSON file if that's the opinion though.

**Comment by darahayes** [comment]
@TommyJ1994 thanks for your input. I agree it's not ideal, as the generated file is massive. I've updated the name as per your suggestion.

**Comment by tomjackman** [comment]
@darahayes Cool, thanks. I condensed down the `secure-app-partial-export-realm.json` to ~100 lines and created a [Gist](https://gist.github.com/TommyJ1994/8a9d7283cf14dafd23681746a049cc1d). Can you check if this works ok? It imports Clients, Groups and Roles.

**Comment by darahayes** [comment]
@TommyJ1994 that's amazing! @aliok Because you're working on the mobile side, when you get a chance could you try out the linked file and see if the mobile application can successfully talk to the backend + keycloak?

**Comment by darahayes** [comment]
@TommyJ1994 Changes seem good to me, I've updated the file with the contents of your gist 👍

**Review by tomjackman — APPROVED** [review]

**Comment by aliok** [comment]
sorry guys didn't have time to test this. I will check it next time I set up the whole thing.

**Pull request merged**
