### PR TITLE
feat(api-server): read keycloak config from file

### PR DESCRIPTION
**Pull request by darahayes**
Related ticket: https://issues.jboss.org/browse/AEROGEAR-2434

I basically followed the same implementation that's in fh-sync-server. It reads the keycloak config from a well known location. This location can still be overridden via an env variable (this is the same in sync).

If a keycloak config file is not found, then initialize the server without the keycloak related middlewares.

I've added a folder called `config` that contains two different keycloak config files. One running the app locally and one for running the app in docker-compose.

The app can be started locally with `KEYCLOAK_CONFIG_PATH=./config/keycloak.json npm start`

Lastly, I made one tiny change to the Openshift template under the minishift-mobile-addon directory to make the `API_SERVER_HOST` variable not required because I found that setting this manually (as opposed to leaving Openshift to generate it) made the service unreachable. It can still be set though if it works for others.

### CODE REVIEW

**Comment by david-martin** [comment]
@darahayes I think we can look for a well defined mount point for the secret instead of the path being specified in the env var.
The Pod Preset we create after the keycloak binding will mount the secret into the pod where this node server is running, so we'll know where to look.

**Comment by darahayes** [comment]
@david-martin sounds good to me. I was just conscious that the default config here is probably being depended upon by the local dev workflow, demos or associated documentation so I avoided changing the existing behaviour.

If we read from a well defined location and the file does not exist should we fallback to the default config that already exists? This will surely preserve the local dev workflow but it also means that this service could accidentally be deployed with a 'dev' config if the file does not exist.

The other approach we could take is to exit the process if the file is not found, but this makes local development slightly more painful.

It seems like a really trivial thing to get so hung up on but this will eventually be experienced by end users.

@TommyJ1994 @wei-lee any input? You guys would have more context with this specific app.

**Comment by david-martin** [comment]
FYI, here's how it was done for fh-sync-server
https://github.com/feedhenry/fh-sync-server/blob/master/app.js#L37-L42

**Comment by tomjackman** [comment]
@darahayes I don't think we have too much referencing the config in terms of demos/docs as this change is related to only the API Server which is lightweight and not a primary part of the mobile security work.

**Comment by darahayes** [comment]
Looks like that might be the way to go. Thanks!

**Comment by darahayes** [comment]
@TommyJ1994 @wei-lee @david-martin I'd love if you could check out the latest changes if you have the time.

**Comment by tomjackman** [comment]
@darahayes Don't see any issues with it, so LGTM to merge. :+1:

**Review by tomjackman — APPROVED** [review]

**Pull request merged**
