### PR TITLE
Update links to new iOS template repo

### PR DESCRIPTION
**Pull request by jhellar**
## Motivation

https://issues.jboss.org/browse/AEROGEAR-2519

## Changes

Update links to new iOS template repo

### CODE REVIEW

**Comment by jhellar** [comment]
ping @TommyJ1994

**Comment by tomjackman** [comment]
@jhellar Is it possible to also add new screenshots for the iOS template? The current ones we have show the old UI - https://github.com/feedhenry/mobile-security/tree/master/docs/assets

**Comment by jhellar** [comment]
@TommyJ1994 should be updated now.

**Review by tomjackman — APPROVED** [review]
Think this LGTM.

**Comment by jhellar** [comment]
@TommyJ1994 can you merge this as well?

**Comment by tomjackman** [comment]
@jhellar Sure.

**Pull request merged**
